version: '3.4'
services:
  solana.avado.dnp.dappnode.eth:
    build:
      context: ./build
      args:
        VERSION: 1.8.14
    image: 'solana.avado.dnp.dappnode.eth:0.0.1'
    restart: always
    volumes:
      - 'data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '8899:8899'
      - '8900:8890'
volumes:
  data: {}
